all:
  vars:
    ansible_user: root
    ansible_connection: ssh
    ansible_ssh_private_key_file: /home/fred/.ssh/workshop01

  hosts: 
    mydroplet:
      ansible_host: 178.128.222.46
      code_server_password: abc@123
      code_server_domain: code-{{ansible_host}}.nip.io